# Generated by Django 4.2 on 2023-05-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='aula',
        ),
        migrations.DeleteModel(
            name='Aula',
        ),
        migrations.DeleteModel(
            name='Presenca',
        ),
    ]
